### ISSUE TITLE
Roadmap to Version 2.0

### ISSUE THREAD

**Issue by vasilakisfil** [kollegorna/active_hash_relation#13]
Version 1.0 is stable but some features are missing. These are the milestones to version 2.0:
- [x] ~~JSONAPI optional support (filter param)~~
- [x] OR support (https://github.com/kollegorna/active_hash_relation/issues/10, fixed in #24 )
- [x] NOT support (fixed in #25)
- [x] NULL support (fixed in #16)
- [x] Add extended tests (fixed in #22 and #23)
- [x] ~~Possible remove filter classes (never used them except SKL)~~
- [x] ~~Pagination support~~ (I think pagination is out of scope of this gem)
- [x] Rails 5 support (fixed in #22 and #23)
- [x] Simplify sorting (fixed in #26)
- [x] Multiple sorting columns
- [x] Params on scopes
- [x] `eq` for numbers/floats/dates/datetimes

I will create a new branch named develop to start working on those features.

**Comment by vasilakisfil** [comment]
Ok! Seems we are ready to ship 2.0 version :)

I decided against at having in-built JSONAPI support as I feel this does not belongs in the scopes of this gem. However if you disagree open an issue or make a PR :)

Also, I decided not removing the filter classes as I feel the complexity they add is minimal and in huge projects are very helpful.
